"""Initial migration

Revision ID: c9cb3e53add4
Revises:
Create Date: 2025-11-26 13:28:37.918473

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9cb3e53add4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "freelance_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "micro_bnc",
                "micro_bic",
                "reel_bnc",
                "reel_bic",
                "eurl",
                "sasu",
                name="freelance_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "family_situation",
            sa.Enum(
                "single",
                "married",
                "pacs",
                "divorced",
                "widowed",
                name="family_situation_enum",
            ),
            nullable=False,
        ),
        sa.Column("nb_parts", sa.Float(), nullable=False),
        sa.Column("annual_revenue", sa.Float(), nullable=False),
        sa.Column("annual_expenses", sa.Float(), nullable=False),
        sa.Column("social_contributions", sa.Float(), nullable=False),
        sa.Column("other_income", sa.Float(), nullable=False),
        sa.Column("existing_deductions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_freelance_profiles")),
    )
    op.create_table(
        "tax_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "avis_imposition",
                "declaration_2042",
                "urssaf",
                "bnc",
                "bic",
                "per",
                "assurance_vie",
                "lmnp",
                "other",
                name="document_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "processing",
                "processed",
                "failed",
                name="document_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("extracted_fields", sa.JSON(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_documents")),
    )
    op.create_table(
        "tax_calculations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("gross_income", sa.Float(), nullable=False),
        sa.Column("net_taxable_income", sa.Float(), nullable=False),
        sa.Column("nb_parts", sa.Float(), nullable=False),
        sa.Column("quotient_familial", sa.Float(), nullable=False),
        sa.Column("brackets", sa.JSON(), nullable=False),
        sa.Column("gross_tax", sa.Float(), nullable=False),
        sa.Column("tax_reductions", sa.JSON(), nullable=False),
        sa.Column("net_tax", sa.Float(), nullable=False),
        sa.Column("revenu_fiscal_reference", sa.Float(), nullable=False),
        sa.Column("social_contributions", sa.Float(), nullable=False),
        sa.Column("total_fiscal_burden", sa.Float(), nullable=False),
        sa.Column("effective_rate", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["freelance_profiles.id"],
            name=op.f("fk_tax_calculations_profile_id_freelance_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_calculations")),
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("calculation_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "regime_change",
                "per_contribution",
                "lmnp_investment",
                "fcpi_fip",
                "girardin",
                "company_structure",
                "deduction_optimization",
                "other",
                name="recommendation_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("estimated_tax_savings", sa.Float(), nullable=False),
        sa.Column("required_investment", sa.Float(), nullable=False),
        sa.Column("roi_percentage", sa.Float(), nullable=True),
        sa.Column(
            "risk_level",
            sa.Enum("low", "medium", "high", name="risk_level_enum"),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("action_steps", sa.JSON(), nullable=False),
        sa.Column("deadlines", sa.JSON(), nullable=True),
        sa.Column("required_documents", sa.JSON(), nullable=False),
        sa.Column("eligibility_criteria", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["tax_calculations.id"],
            name=op.f("fk_recommendations_calculation_id_tax_calculations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendations")
    op.drop_table("tax_calculations")
    op.drop_table("tax_documents")
    op.drop_table("freelance_profiles")
    # ### end Alembic commands ###
